import type { WorkRecord } from "./models";
const base={detailedNotes:"",status:"complete" as const,output:"",outcome:"",nextStep:"",followUpNeeded:false,followUpDate:null,isSample:true,createdAt:"2026-08-26T08:00:00.000Z",modifiedAt:"2026-08-26T08:00:00.000Z"};
export const SAMPLE_RECORDS:WorkRecord[]=[
{...base,appId:"sample-steels",title:"District STEELS planning meeting",activityDate:"2026-08-26",activityType:"District meeting",description:"Planned next steps for local STEELS implementation.",durationMinutes:60,projectIds:["project-steels"],organizationIds:["org-north-valley"],categoryIds:["cat-district","cat-steels","cat-planning"],reach:{educatorsLeaders:5,studentsFamilies:0,workforceCommunity:0,other:0},output:"Draft implementation roadmap",outcome:"District team identified two priority actions.",nextStep:"Send STEELS resources",followUpNeeded:true,followUpDate:"2026-08-28",orbit:{reportable:true,primaryDeliverable:"B",supportingDeliverables:["D"],stemPocMinutes:60,tacMinutes:0,evidence:"Planning notes and draft roadmap"}},
{...base,appId:"sample-ai",title:"AI professional learning session",activityDate:"2026-08-26",activityType:"Professional learning",description:"Facilitated a practical responsible-AI learning session.",durationMinutes:120,projectIds:["project-ai"],organizationIds:["org-regional"],categoryIds:["cat-pl","cat-ai"],reach:{educatorsLeaders:24,studentsFamilies:0,workforceCommunity:0,other:0},output:"Workshop and resource guide",outcome:"Participants drafted classroom use guidelines.",orbit:{reportable:true,primaryDeliverable:"C",supportingDeliverables:["D"],stemPocMinutes:120,tacMinutes:0,evidence:"Session materials and participant reflection"}},
{...base,appId:"sample-internal",title:"Internal IU planning meeting",activityDate:"2026-08-26",activityType:"Internal planning",description:"Coordinated fall district-support priorities.",durationMinutes:75,projectIds:[],organizationIds:["org-iu"],categoryIds:["cat-internal","cat-planning"],reach:{educatorsLeaders:0,studentsFamilies:0,workforceCommunity:0,other:4},output:"Prioritized action list",outcome:"Team aligned on September support schedule.",orbit:{reportable:false,primaryDeliverable:null,supportingDeliverables:[],stemPocMinutes:0,tacMinutes:0,evidence:""}},
{...base,appId:"sample-keystone",title:"Keystone STEM Competition planning",activityDate:"2026-08-25",activityType:"Project planning",description:"Reviewed event logistics and challenge timeline.",durationMinutes:90,projectIds:["project-keystone"],organizationIds:["org-iu"],categoryIds:["cat-stem","cat-students","cat-planning"],reach:{educatorsLeaders:3,studentsFamilies:0,workforceCommunity:0,other:0},output:"Updated planning checklist",outcome:"Venue and mentor needs clarified.",orbit:{reportable:true,primaryDeliverable:"F",supportingDeliverables:[],stemPocMinutes:90,tacMinutes:0,evidence:"Planning checklist"}},
{...base,appId:"sample-ecosystem",title:"STEM Ecosystem partner meeting",activityDate:"2026-08-24",activityType:"Partner meeting",description:"Connected regional partners around fall workforce events.",durationMinutes:60,projectIds:["project-ecosystem"],organizationIds:["org-futureworks"],categoryIds:["cat-stem","cat-partnerships"],reach:{educatorsLeaders:2,studentsFamilies:0,workforceCommunity:7,other:0},output:"Shared event concept",outcome:"Three partners volunteered to co-design the event.",nextStep:"Confirm partner roundtable",followUpNeeded:true,followUpDate:"2026-09-02",orbit:{reportable:true,primaryDeliverable:"E",supportingDeliverables:["A"],stemPocMinutes:60,tacMinutes:30,evidence:"Partner meeting notes"}},
{...base,appId:"sample-makerspace",title:"Makerspace student visit",activityDate:"2026-08-21",activityType:"Student program",description:"Hosted a design-and-build experience for middle school students.",durationMinutes:180,projectIds:["project-makerspace"],organizationIds:["org-riverbend"],categoryIds:["cat-stem","cat-students"],reach:{educatorsLeaders:4,studentsFamilies:48,workforceCommunity:2,other:0},output:"Hands-on design challenge",outcome:"Student teams iterated and presented working prototypes.",orbit:{reportable:true,primaryDeliverable:"F",supportingDeliverables:["G"],stemPocMinutes:180,tacMinutes:0,evidence:"Facilitator notes and future photo references"}},
];
