import { env } from "cloudflare:workers";
import { SAMPLE_RECORDS } from "../../../lib/sample-data";
import type { WorkRecord } from "../../../lib/models";

export const dynamic="force-dynamic";
const createTable=`CREATE TABLE IF NOT EXISTS work_records (id INTEGER PRIMARY KEY AUTOINCREMENT,app_id TEXT NOT NULL UNIQUE,title TEXT NOT NULL,activity_date TEXT NOT NULL,activity_type TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',detailed_notes TEXT NOT NULL DEFAULT '',duration_minutes INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'complete',project_ids_json TEXT NOT NULL DEFAULT '[]',organization_ids_json TEXT NOT NULL DEFAULT '[]',category_ids_json TEXT NOT NULL DEFAULT '[]',educator_reach INTEGER NOT NULL DEFAULT 0,student_reach INTEGER NOT NULL DEFAULT 0,partner_reach INTEGER NOT NULL DEFAULT 0,other_reach INTEGER NOT NULL DEFAULT 0,output TEXT NOT NULL DEFAULT '',outcome TEXT NOT NULL DEFAULT '',next_step TEXT NOT NULL DEFAULT '',follow_up_needed INTEGER NOT NULL DEFAULT 0,follow_up_date TEXT,orbit_reportable INTEGER NOT NULL DEFAULT 0,orbit_primary_deliverable TEXT,orbit_supporting_json TEXT NOT NULL DEFAULT '[]',stem_poc_minutes INTEGER NOT NULL DEFAULT 0,tac_minutes INTEGER NOT NULL DEFAULT 0,orbit_evidence TEXT NOT NULL DEFAULT '',is_sample INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,modified_at TEXT NOT NULL)`;
const indexDate="CREATE INDEX IF NOT EXISTS idx_work_records_activity_date ON work_records(activity_date)";
const indexFollowup="CREATE INDEX IF NOT EXISTS idx_work_records_follow_up_date ON work_records(follow_up_date) WHERE follow_up_needed = 1";
const indexOrbit="CREATE INDEX IF NOT EXISTS idx_work_records_orbit_date ON work_records(orbit_reportable,activity_date) WHERE orbit_reportable = 1";
function db(){if(!env.DB)throw new Error("Prototype data store unavailable");return env.DB}
function insertStatement(database:D1Database,record:WorkRecord,ignore=false){const verb=ignore?"INSERT OR IGNORE":"INSERT";return database.prepare(`${verb} INTO work_records (app_id,title,activity_date,activity_type,description,detailed_notes,duration_minutes,status,project_ids_json,organization_ids_json,category_ids_json,educator_reach,student_reach,partner_reach,other_reach,output,outcome,next_step,follow_up_needed,follow_up_date,orbit_reportable,orbit_primary_deliverable,orbit_supporting_json,stem_poc_minutes,tac_minutes,orbit_evidence,is_sample,created_at,modified_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(record.appId,record.title,record.activityDate,record.activityType,record.description,record.detailedNotes,record.durationMinutes,record.status,JSON.stringify(record.projectIds),JSON.stringify(record.organizationIds),JSON.stringify(record.categoryIds),record.reach.educatorsLeaders,record.reach.studentsFamilies,record.reach.workforceCommunity,record.reach.other,record.output,record.outcome,record.nextStep,record.followUpNeeded?1:0,record.followUpDate,record.orbit.reportable?1:0,record.orbit.primaryDeliverable,JSON.stringify(record.orbit.supportingDeliverables),record.orbit.stemPocMinutes,record.orbit.tacMinutes,record.orbit.evidence,record.isSample?1:0,record.createdAt,record.modifiedAt)}
async function initialize(){const database=db();await database.batch([database.prepare(createTable),database.prepare(indexDate),database.prepare(indexFollowup),database.prepare(indexOrbit)]);const count=await database.prepare("SELECT COUNT(*) AS total FROM work_records").first<{total:number}>();if(Number(count?.total??0)===0)await database.batch(SAMPLE_RECORDS.map((record)=>insertStatement(database,record,true)))}
function parseJson(value:unknown):string[]{try{return JSON.parse(String(value??"[]"))}catch{return[]}}
function fromRow(row:Record<string,unknown>):WorkRecord{return{appId:String(row.app_id),title:String(row.title),activityDate:String(row.activity_date),activityType:String(row.activity_type),description:String(row.description),detailedNotes:String(row.detailed_notes),durationMinutes:Number(row.duration_minutes),status:row.status==="draft"?"draft":"complete",projectIds:parseJson(row.project_ids_json),organizationIds:parseJson(row.organization_ids_json),categoryIds:parseJson(row.category_ids_json),reach:{educatorsLeaders:Number(row.educator_reach),studentsFamilies:Number(row.student_reach),workforceCommunity:Number(row.partner_reach),other:Number(row.other_reach)},output:String(row.output),outcome:String(row.outcome),nextStep:String(row.next_step),followUpNeeded:Boolean(row.follow_up_needed),followUpDate:row.follow_up_date?String(row.follow_up_date):null,orbit:{reportable:Boolean(row.orbit_reportable),primaryDeliverable:row.orbit_primary_deliverable?String(row.orbit_primary_deliverable):null,supportingDeliverables:parseJson(row.orbit_supporting_json),stemPocMinutes:Number(row.stem_poc_minutes),tacMinutes:Number(row.tac_minutes),evidence:String(row.orbit_evidence)},isSample:Boolean(row.is_sample),createdAt:String(row.created_at),modifiedAt:String(row.modified_at),syncState:"saved"}}
function valid(record:WorkRecord){return record&&record.appId&&record.title?.trim()&&record.activityDate&&record.activityType&&Number(record.durationMinutes)>0}
export async function GET(){try{await initialize();const result=await db().prepare("SELECT * FROM work_records ORDER BY activity_date DESC,created_at DESC").all();return Response.json(result.results.map((row)=>fromRow(row as Record<string,unknown>)))}catch{return Response.json({error:"Records could not be loaded."},{status:500})}}
export async function POST(request:Request){try{await initialize();const record=await request.json() as WorkRecord;if(!valid(record))return Response.json({error:"Title, activity date, activity type, and duration are required."},{status:400});const existing=await db().prepare("SELECT id FROM work_records WHERE app_id = ?").bind(record.appId).first();if(existing){await db().prepare("UPDATE work_records SET title=?,activity_date=?,activity_type=?,description=?,detailed_notes=?,duration_minutes=?,status=?,project_ids_json=?,organization_ids_json=?,category_ids_json=?,educator_reach=?,student_reach=?,partner_reach=?,other_reach=?,output=?,outcome=?,next_step=?,follow_up_needed=?,follow_up_date=?,orbit_reportable=?,orbit_primary_deliverable=?,orbit_supporting_json=?,stem_poc_minutes=?,tac_minutes=?,orbit_evidence=?,is_sample=?,modified_at=? WHERE app_id=?").bind(record.title,record.activityDate,record.activityType,record.description,record.detailedNotes,record.durationMinutes,record.status,JSON.stringify(record.projectIds),JSON.stringify(record.organizationIds),JSON.stringify(record.categoryIds),record.reach.educatorsLeaders,record.reach.studentsFamilies,record.reach.workforceCommunity,record.reach.other,record.output,record.outcome,record.nextStep,record.followUpNeeded?1:0,record.followUpDate,record.orbit.reportable?1:0,record.orbit.primaryDeliverable,JSON.stringify(record.orbit.supportingDeliverables),record.orbit.stemPocMinutes,record.orbit.tacMinutes,record.orbit.evidence,record.isSample?1:0,record.modifiedAt,record.appId).run()}else await insertStatement(db(),record).run();return Response.json({...record,syncState:"saved"})}catch{return Response.json({error:"The record could not be saved. Your entry remains open."},{status:500})}}
